### PR TITLE
arcswap: fix imbalance violations

### LINKED ISSUE #197: arcswap: better ensure imbalance thresholds are not exceeded
Follow up of #193

### PR DESCRIPTION
**Pull request by hhirtz**
Now arcswap works in passes (bulk synchronous). Each pass does:

- copy the part weights
- threads make the moves
- aggregate the updated part weights from threads
- reduce to the updated global part weights (avoid having to compute the part weights from scratch)

... until a pass has no gain. This should fix the end conditions, albeit performance is yet to be measured.

This also changes the max_part_weight (thread-local maximum for the part weights) so that is accounts for all threads correctly.

This commit fixes the bipart violations, but 128-part tests show that it's not totally fixed.

Closes #197 

## TODO

- [ ] remove the `Debug` constraint on `AsWeight`

### CODE REVIEW

**Comment by hhirtz** [comment]
bi-part:
histo2

128-part:
histo

**Comment by hhirtz** [comment]
When all weights are equal (`constant,1` distribution), arcswap respects the imbalance threshold if the input partition has acceptable balance already. However, on the random partition, arcswap worsen the balance while it shouldn't.

histo

File: src/algorithms/arc_swap.rs [hunk 1]
```diff
@@ -103,164 +101,204 @@
...
+        metadata.pass_count += 1;
+
+        // `part_weights` changes at the end of each pass, so `thread_max_pws`
+        // needs to be updated here.
+        for (max_pw, pw) in thread_max_pws.iter_mut().zip(&part_weights) {
+            *max_pw = *pw
+                + W::from_f64((max_part_weight - *pw).to_f64().unwrap() / thread_count as f64)
+                    .unwrap();
+        }
+
```
Comment (cedricchevalier19) [inline src/algorithms/arc_swap.rs:245]: I am still not convinced by this kind of over constraint.

File: src/algorithms/arc_swap.rs [hunk 2]
```diff
@@ -272,7 +310,8 @@
     Self: std::fmt::Debug + Copy + PartialOrd + Send + Sync + num::Zero,
     Self: std::iter::Sum + num::FromPrimitive + num::ToPrimitive,
     Self: std::ops::AddAssign + std::ops::SubAssign + std::ops::Sub<Output = Self>,
-    Self: std::ops::Div<Output = Self>,
+    Self: std::ops::Mul<Output = Self> + std::ops::Div<Output = Self>,
```
Comment (cedricchevalier19) [inline src/algorithms/arc_swap.rs:313]: It is unfortunate that we require this far into coupe. To me, it should be more logical to only have max_weights for each part as an entry.

**Review by cedricchevalier19 — APPROVED** [review]
Two remarks, not really things to fix now.

File: src/algorithms/arc_swap.rs (hunk 1 above)
Comment (hhirtz) [reply src/algorithms/arc_swap.rs:245]: I agree this is overly restrictive. The problem is that there is no way to predict how much and where threads will move weights before the pass starts.

To relax this constraint, we would need either:
1. synchronize the `part_weights` array and greatly reduce the performance,
2. do some prior work to make it so threads don't all move vertices to one part, somehow?

Please note that, since `thread_max_pws` is updated before each pass, so any imbalance-breaking move can be retried at a later pass if necessary.

File: src/algorithms/arc_swap.rs (hunk 2 above)
Comment (hhirtz) [reply src/algorithms/arc_swap.rs:313]: `max_part_weight` is computed from either the `max_imbalance` input, or from the input partition (the weight of the overweight part) otherwise.

We can totally add another input to control its value, though I would like to postpone this for another PR.
